export const APP_ERROR_CODE = {
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  HTTP_EXCEPTION: 'HTTP_EXCEPTION',
} as const;

export type AppErrorCode = (typeof APP_ERROR_CODE)[keyof typeof APP_ERROR_CODE];

export const TRANSLATED_ERROR_CODES = [
  APP_ERROR_CODE.BAD_REQUEST,
  APP_ERROR_CODE.UNAUTHORIZED,
  APP_ERROR_CODE.FORBIDDEN,
  APP_ERROR_CODE.NOT_FOUND,
  APP_ERROR_CODE.CONFLICT,
  APP_ERROR_CODE.UNPROCESSABLE_ENTITY,
  APP_ERROR_CODE.TOO_MANY_REQUESTS,
  APP_ERROR_CODE.INTERNAL_SERVER_ERROR,
] as const;
